version: '3'
services:
  web:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db

